### ISSUE TITLE
Use meta for response headers, contentType, statusCode...etc

### ISSUE THREAD

**Issue by icebob** [moleculerjs/moleculer-web#35]
Since [Moleculer v.012](https://github.com/moleculerjs/moleculer/blob/master/CHANGELOG.md#metadata-is-sent-back-to-requester) `ctx.meta` comes back to the caller. It means requests send context meta information back to API Gateway, like response status code, response headers, response content type...etc.

**Meta keys what API Gateway will process:**

- [x] `ctx.meta.$responseType` - set `Content-Type` in response
- [x] `ctx.meta.$responseHeaders` - set custom response headers
- [x] `ctx.meta.$responseStatus` - set HTTP status code in response
- [x] `ctx.meta.$location` - redirect location when the `$responseStatus` is 3xx

**Example**
```js
{
    exportData(ctx) {
        // Set meta for API GW
        ctx.meta.$responseStatus = 200;
        ctx.meta.$responseType = "text/csv; charset=utf-8";
        ctx.meta.$responseHeaders = {
            "Content-Disposition": 'attachment; filename=\"data.csv\"'
        }

        // Return data
        return this.getAllRows();
    }
}
```

**Comment by icebob** [comment]
Will be released in 0.7
